### ISSUE TITLE
【BUG】前端传null值时DTO解析失败，程序报错

### ISSUE THREAD

**Issue by LazySleep** [tw2066/api-docs#11]
dto
```php
<?php


namespace App\Dto\Admin\Carousel;


use App\Dto\BaseDto;
use Hyperf\ApiDocs\Annotation\ApiModelProperty;
use Hyperf\DTO\Annotation\Validation\Validation;

class CarouselUpdateDto extends BaseDto {

    #[ApiModelProperty('分类')]
    public $category_id;

    #[ApiModelProperty('图片')]
    #[Validation('array')]
    public $imgs;

    #[ApiModelProperty('链接类型')]
    public $type;

    #[ApiModelProperty('链接')]
    public $link;

    #[ApiModelProperty('启用状态')]
    public $enable;

    #[ApiModelProperty('排序值')]
    public $sort;
}
```
数据
```json
{"carousel_id":1,"category_id":8,"imgs":[{"filename":"uploadlib-.png","type":"image","url":"http://127.0.0.1:9601/res-lib/upload/uploadlib-1653622489404.20221123143058.png","preview_url":"http://127.0.0.1:9601/res-lib/upload/uploadlib-1653622489404.20221123143058.png"}],"type":"none","link":null,"enable":1,"sort":1,"created_at":"2023-01-13 16:39:51","updated_at":"2023-01-13 17:55:31","deleted_at":null}

```
错误日志
```
Fatal error: Uncaught JsonMapper_Exception: JSON property "link" in class "App\Dto\Admin\Carousel\CarouselUpdateDto" must not be NULL in /data/www/hyperf-admin/vendor/netresearch/jsonmapper/src/JsonMapper.php:216
Stack trace:
#0 /data/www/hyperf-admin/vendor/tangwei/dto/src/Mapper.php(17): JsonMapper->map(Array, Object(App\Dto\Admin\Carousel\CarouselUpdateDto))
#1 /data/www/hyperf-admin/vendor/tangwei/dto/src/Middleware/CoreMiddleware.php(119): Hyperf\DTO\Mapper::map(Array, Object(App\Dto\Admin\Carousel\CarouselUpdateDto))
#2 /data/www/hyperf-admin/vendor/tangwei/dto/src/Middleware/CoreMiddleware.php(72): Hyperf\DTO\Middleware\CoreMiddleware->validateAndMap('App\\Controller\\...', 'dto', 'App\\Dto\\Admin\\C...', Object(App\Dto\Admin\Carousel\CarouselUpdateDto))
#3 /data/www/hyperf-admin/vendor/tangwei/dto/src/Middleware/CoreMiddleware.php(25): Hyperf\DTO\Middleware\CoreMiddleware->getInjections(Array, 'App\\Controller\\...', Array)
#4 /data/www/hyperf-admin/vendor/hyperf/http-server/src/CoreMiddleware.php(160): Hyperf\DTO\Middleware\CoreMiddleware->parseMethodParameters('App\\Controller\\...', 'update', Array)
#5 /data/www/hyperf-admin/vendor/hyperf/http-server/src/CoreMiddleware.php(113): Hyperf\HttpServer\CoreMiddleware->handleFound(Object(Hyperf\HttpServer\Router\Dispatched), Object(Hyperf\HttpMessage\Server\Request))
#6 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\HttpServer\CoreMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#7 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#8 /data/www/hyperf-admin/runtime/container/proxy/App_Core_RBAC_Middleware_RBACMiddleware.proxy.php(49): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#9 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): App\Core\RBAC\Middleware\RBACMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#10 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#11 /data/www/hyperf-admin/app/Core/Auth/Aspect/AuthMiddlewareAspect.php(45): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#12 /data/www/hyperf-admin/vendor/hyperf/di/src/Aop/Pipeline.php(30): App\Core\Auth\Aspect\AuthMiddlewareAspect->process(Object(Hyperf\Di\Aop\ProceedingJoinPoint))
#13 /data/www/hyperf-admin/vendor/hyperf/utils/src/Pipeline.php(95): Hyperf\Di\Aop\Pipeline->Hyperf\Di\Aop\{closure}(Object(Hyperf\Di\Aop\ProceedingJoinPoint))
#14 /data/www/hyperf-admin/vendor/hyperf/di/src/Aop/ProxyTrait.php(86): Hyperf\Utils\Pipeline->then(Object(Closure))
#15 /data/www/hyperf-admin/vendor/hyperf/di/src/Aop/ProxyTrait.php(29): Qbhy\HyperfAuth\AuthMiddleware::handleAround(Object(Hyperf\Di\Aop\ProceedingJoinPoint))
#16 /data/www/hyperf-admin/runtime/container/proxy/Qbhy_HyperfAuth_AuthMiddleware.proxy.php(49): Qbhy\HyperfAuth\AuthMiddleware::__proxyCall('Qbhy\\HyperfAuth...', 'process', Array, Object(Closure))
#17 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Qbhy\HyperfAuth\AuthMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#18 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#19 /data/www/hyperf-admin/vendor/hyperf/validation/src/Middleware/ValidationMiddleware.php(83): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#20 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\Validation\Middleware\ValidationMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#21 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#22 /data/www/hyperf-admin/runtime/container/proxy/App_Core_RespFmt_Middleware_RespFmtMiddleware.proxy.php(35): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#23 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): App\Core\RespFmt\Middleware\RespFmtMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#24 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#25 /data/www/hyperf-admin/runtime/container/proxy/App_Core_Utils_Middleware_LanguageMiddleware.proxy.php(30): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#26 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): App\Core\Utils\Middleware\LanguageMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#27 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#28 /data/www/hyperf-admin/app/Core/Utils/Middleware/CorsMiddleware.php(32): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#29 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): App\Core\Utils\Middleware\CorsMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#30 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#31 /data/www/hyperf-admin/vendor/hyperf/dispatcher/src/HttpDispatcher.php(40): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#32 /data/www/hyperf-admin/vendor/hyperf/http-server/src/Server.php(117): Hyperf\Dispatcher\HttpDispatcher->dispatch(Object(Hyperf\HttpMessage\Server\Request), Array, Object(Hyperf\DTO\Middleware\CoreMiddleware))
#33 {main}
  thrown in /data/www/hyperf-admin/vendor/netresearch/jsonmapper/src/JsonMapper.php on line 216
[2023-01-13 18:06:29 *1265.0]   WARNING Channel::~Channel() (ERRNO 10003): channel is destroyed, 2 consumers will be discarded
PHP Fatal error:  Uncaught Swoole\Error: API must be called in the coroutine in /data/www/hyperf-admin
```

**Comment by tw2066** [comment]
https://github.com/tw2066/dto/commit/d154741a01637f5e5509122f34cbe7c2d55eea4e

**Comment by tw2066** [comment]
composer update 更新 验证

**Comment by LazySleep** [comment]
可以了，👍
