### ISSUE TITLE
securitySchemes中使用type = http时 无法使用schema属性

### ISSUE THREAD

**Issue by LazySleep** [tw2066/api-docs#6]
配置如下
![image](https://user-images.githubusercontent.com/32838949/205429512-50cefcc4-ed50-4e0d-8990-6248c4a75b65.png)

报错如下
```
PHP Fatal error:  Uncaught Error: Call to undefined method phpDocumentor\Reflection\DocBlock\Tags\See::getType() in /data/www/hyperf-admin/vendor/tangwei/dto/src/JsonMapper.php:177
Stack trace:
#0 /data/www/hyperf-admin/vendor/tangwei/dto/src/JsonMapper.php(100): Hyperf\DTO\JsonMapper->parseAnnotationsNew(Object(ReflectionClass), Object(ReflectionProperty), '/**\n     * The ...')
#1 /data/www/hyperf-admin/vendor/netresearch/jsonmapper/src/JsonMapper.php(167): Hyperf\DTO\JsonMapper->inspectProperty(Object(ReflectionClass), 'scheme')
#2 /data/www/hyperf-admin/vendor/tangwei/dto/src/Mapper.php(17): JsonMapper->map(Array, Object(OpenApi\Attributes\SecurityScheme))
#3 /data/www/hyperf-admin/vendor/tangwei/apidocs/src/Swagger/SwaggerOpenApi.php(104): Hyperf\DTO\Mapper::map(Array, Object(OpenApi\Attributes\SecurityScheme))
#4 /data/www/hyperf-admin/vendor/tangwei/apidocs/src/Swagger/SwaggerOpenApi.php(43): Hyperf\ApiDocs\Swagger\SwaggerOpenApi->setComponentsSecuritySchemes()
#5 /data/www/hyperf-admin/vendor/tangwei/apidocs/src/Listener/AfterDtoStartListener.php(52): Hyperf\ApiDocs\Swagger\SwaggerOpenApi->init()
#6 /data/www/hyperf-admin/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\ApiDocs\Listener\AfterDtoStartListener->process(Object(Hyperf\DTO\Event\AfterDtoStart))
#7 /data/www/hyperf-admin/vendor/tangwei/dto/src/BeforeServerListener.php(63): Hyperf\Event\EventDispatcher->dispatch(Object(Hyperf\DTO\Event\AfterDtoStart))
#8 /data/www/hyperf-admin/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\DTO\BeforeServerListener->process(Object(Hyperf\Framework\Event\BeforeServerStart))
#9 /data/www/hyperf-admin/vendor/hyperf/server/src/Server.php(131): Hyperf\Event\EventDispatcher->dispatch(Object(Hyperf\Framework\Event\BeforeServerStart))
#10 /data/www/hyperf-admin/vendor/hyperf/server/src/Server.php(72): Hyperf\Server\Server->initServers(Object(Hyperf\Server\ServerConfig))
#11 /data/www/hyperf-admin/vendor/hyperf/server/src/ServerFactory.php(56): Hyperf\Server\Server->init(Object(Hyperf\Server\ServerConfig))
#12 /data/www/hyperf-admin/vendor/hyperf/server/src/Command/StartServer.php(52): Hyperf\Server\ServerFactory->configure(Array)
#13 /data/www/hyperf-admin/vendor/symfony/console/Command/Command.php(298): Hyperf\Server\Command\StartServer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /data/www/hyperf-admin/vendor/symfony/console/Application.php(1042): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /data/www/hyperf-admin/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Hyperf\Server\Command\StartServer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /data/www/hyperf-admin/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /data/www/hyperf-admin/bin/hyperf.php(23): Symfony\Component\Console\Application->run()
#18 /data/www/hyperf-admin/bin/hyperf.php(24): {closure}()
#19 /data/www/hyperf-admin/vendor/hyperf/watcher/watcher.php(22): require_once('/data/www/hyper...')
#20 {main}
  thrown in /data/www/hyperf-admin/vendor/tangwei/dto/src/JsonMapper.php on line 177

Fatal error: Uncaught Error: Call to undefined method phpDocumentor\Reflection\DocBlock\Tags\See::getType() in /data/www/hyperf-admin/vendor/tangwei/dto/src/JsonMapper.php:177
Stack trace:
#0 /data/www/hyperf-admin/vendor/tangwei/dto/src/JsonMapper.php(100): Hyperf\DTO\JsonMapper->parseAnnotationsNew(Object(ReflectionClass), Object(ReflectionProperty), '/**\n     * The ...')
#1 /data/www/hyperf-admin/vendor/netresearch/jsonmapper/src/JsonMapper.php(167): Hyperf\DTO\JsonMapper->inspectProperty(Object(ReflectionClass), 'scheme')
#2 /data/www/hyperf-admin/vendor/tangwei/dto/src/Mapper.php(17): JsonMapper->map(Array, Object(OpenApi\Attributes\SecurityScheme))
#3 /data/www/hyperf-admin/vendor/tangwei/apidocs/src/Swagger/SwaggerOpenApi.php(104): Hyperf\DTO\Mapper::map(Array, Object(OpenApi\Attributes\SecurityScheme))
#4 /data/www/hyperf-admin/vendor/tangwei/apidocs/src/Swagger/SwaggerOpenApi.php(43): Hyperf\ApiDocs\Swagger\SwaggerOpenApi->setComponentsSecuritySchemes()
#5 /data/www/hyperf-admin/vendor/tangwei/apidocs/src/Listener/AfterDtoStartListener.php(52): Hyperf\ApiDocs\Swagger\SwaggerOpenApi->init()
#6 /data/www/hyperf-admin/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\ApiDocs\Listener\AfterDtoStartListener->process(Object(Hyperf\DTO\Event\AfterDtoStart))
#7 /data/www/hyperf-admin/vendor/tangwei/dto/src/BeforeServerListener.php(63): Hyperf\Event\EventDispatcher->dispatch(Object(Hyperf\DTO\Event\AfterDtoStart))
#8 /data/www/hyperf-admin/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\DTO\BeforeServerListener->process(Object(Hyperf\Framework\Event\BeforeServerStart))
#9 /data/www/hyperf-admin/vendor/hyperf/server/src/Server.php(131): Hyperf\Event\EventDispatcher->dispatch(Object(Hyperf\Framework\Event\BeforeServerStart))
#10 /data/www/hyperf-admin/vendor/hyperf/server/src/Server.php(72): Hyperf\Server\Server->initServers(Object(Hyperf\Server\ServerConfig))
#11 /data/www/hyperf-admin/vendor/hyperf/server/src/ServerFactory.php(56): Hyperf\Server\Server->init(Object(Hyperf\Server\ServerConfig))
#12 /data/www/hyperf-admin/vendor/hyperf/server/src/Command/StartServer.php(52): Hyperf\Server\ServerFactory->configure(Array)
#13 /data/www/hyperf-admin/vendor/symfony/console/Command/Command.php(298): Hyperf\Server\Command\StartServer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /data/www/hyperf-admin/vendor/symfony/console/Application.php(1042): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /data/www/hyperf-admin/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Hyperf\Server\Command\StartServer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /data/www/hyperf-admin/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /data/www/hyperf-admin/bin/hyperf.php(23): Symfony\Component\Console\Application->run()
#18 /data/www/hyperf-admin/bin/hyperf.php(24): {closure}()
#19 /data/www/hyperf-admin/vendor/hyperf/watcher/watcher.php(22): require_once('/data/www/hyper...')
#20 {main}
  thrown in /data/www/hyperf-admin/vendor/tangwei/dto/src/JsonMapper.php on line 177
Stop server success.

```

我希望实现Bearer格式的token

**Comment by tw2066** [comment]
```
                [
                    'securityScheme' => 'Authorization',
                    'type' => 'apiKey',
                    'in' => 'header',
                    'name' => 'Authorization',
                ]
```

这样的配置就可以实现  Bearer格式的token

> token前面加上`Bearer`+空格

**Comment by tw2066** [comment]
```
                [
                    'securityScheme' => 'bearerAuth',
                    'type' => 'http',
                    'scheme' => 'bearer',
                ],
```
已修复
https://github.com/tw2066/dto/commit/55e23cc4f90536666e54af58a5c19e538a66139e

**Comment by LazySleep** [comment]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/32838949/212587862-21932945-9bdc-4edc-acf8-8cf06bb9c14c.png">
这样设置后生成的json还是Authorization
<img width="896" alt="image" src="https://user-images.githubusercontent.com/32838949/212587891-79e20146-0081-40e0-a243-c3f92da0b3ae.png">
